{{- if or .Values.postgresql.enabled (not .Values.postgresql.external.existingSecret) }}
{{- $secretName := include "trix.postgresql.secretName" . }}
{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace $secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  labels:
    {{- include "trix.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  username: {{ .Values.postgresql.user | b64enc | quote }}
  {{- if and $existingSecret (index $existingSecret.data "password") }}
  password: {{ index $existingSecret.data "password" }}
  {{- else }}
  password: {{ .Values.postgresql.password | default (randAlphaNum 24) | b64enc | quote }}
  {{- end }}
  database: {{ .Values.postgresql.database | b64enc | quote }}
  {{- else }}
  username: {{ .Values.postgresql.external.user | b64enc | quote }}
  password: {{ .Values.postgresql.external.password | b64enc | quote }}
  database: {{ .Values.postgresql.external.database | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.notifications.slack.enabled (not .Values.notifications.slack.existingSecret) .Values.notifications.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trix.fullname" . }}-slack
  labels:
    {{- include "trix.labels" . | nindent 4 }}
type: Opaque
data:
  webhook-url: {{ .Values.notifications.slack.webhookUrl | b64enc | quote }}
{{- end }}
---
{{- if and .Values.notifications.saas.enabled (not .Values.notifications.saas.existingSecret) .Values.notifications.saas.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trix.fullname" . }}-saas
  labels:
    {{- include "trix.labels" . | nindent 4 }}
type: Opaque
data:
  api-key: {{ .Values.notifications.saas.apiKey | b64enc | quote }}
{{- end }}
