{{- if or .Values.postgresql.enabled (not .Values.postgresql.external.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trix.postgresql.secretName" . }}
  labels:
    {{- include "trix.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.postgresql.enabled }}
  username: {{ .Values.postgresql.user | b64enc | quote }}
  password: {{ .Values.postgresql.password | default (randAlphaNum 24) | b64enc | quote }}
  database: {{ .Values.postgresql.database | b64enc | quote }}
  {{- else }}
  username: {{ .Values.postgresql.external.user | b64enc | quote }}
  password: {{ .Values.postgresql.external.password | b64enc | quote }}
  database: {{ .Values.postgresql.external.database | b64enc | quote }}
  {{- end }}
{{- end }}
---
{{- if and .Values.notifications.slack.enabled (not .Values.notifications.slack.existingSecret) .Values.notifications.slack.webhookUrl }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "trix.fullname" . }}-slack
  labels:
    {{- include "trix.labels" . | nindent 4 }}
type: Opaque
data:
  webhook-url: {{ .Values.notifications.slack.webhookUrl | b64enc | quote }}
{{- end }}
